== README

=== Farsi Learn

Farsi learn is a software allowing a non technical experts to sketch
rules and logic steps needed for the task of transliteration of Farsi.

We have created this system to speed up and make flexible this general
part of the work.

While the language specialist can design and try easily his own rules,
the developer implements the code corresponding to the rules. This way
both tasks and roles are well defined and confined.

=== Learning Strategy
Any lucidchart diagram  is encoded and "learnt" as a graph.


==== Graph Parsed

Example data:
____
resources/TestFarsiTrans.csv
resources/TestFarsiTrans.png
____


==== Python Dependencies

Has to be ran alongside the python dependancies of farsi branch
[source,bash]
----
ENV[``PYTHON''] = ``…my python path with hazm installed…''
import Pkg; Pkg.add(``PyCall''); Pkg.build(``PyCall'')
----

==== Ressources Dependencies
Farsi resources can be found on https://github.com/secryst/rababa-models/releases[secryst] and manually downloaded there. Assets are to be put under resources. Alternatively, run the following commands:
[source,bash]
----
curl -sSL https://github.com/secryst/rababa-models/releases/download/untagged-d9108f5298deeb17ecac/farsi_assets.pickle -o resources/farsi_assets.pickle
curl -sSL https://github.com/secryst/rababa-models/releases/download/untagged-d9108f5298deeb17ecac/postagger.model -o resources/postagger.model
----

==== Install Julia

https://julialang.org/downloads/[julia downloads]

==== Julia Dependencies

[source,bash]
----
julia packageInstall.jl
----

==== Commands

* Train
[source,bash]
----
julia train.jl –-help
julia train.jl --path-lucidchart-csv resources/TestFarsiTrans.csv --brain-entry transliterator --path-model resources/TestFarsiTrans.dat
----

* Transliterate single string (with debugging mode)
[source,bash]
----
julia transliterateSingleString.jl –-help
julia transliterateSingleString.jl --path-model resources/TestFarsiTrans.dat --farsi-text یویو --pos-tagging N
----

* Run Tests (data data/tests.csv)

run diacritization on file:
[source,bash]
----
julia run.jl –-help
julia run.jl --path-model resources/TestFarsiTrans.dat --file-name data/test_poems.txt
----

run tests, with scores and error summary:
[source,bash]
----
julia run.jl --path-model resources/TestFarsiTrans.dat --file-name test
----
