= Middle-Eastern Language Diacritization in Ruby with Rababa

== Try out Rababa

* Install the Gems listed below
* Download a Ruby model on https://github.com/secryst/rababa-models[releases]

== Usage

=== Install

[source,sh]
----
gem install rababa
----

=== Download the ONNX models & configs

from:
For Arabic:
- https://github.com/secryst/rababa-models/releases/tag/0.1

For Hebrew:
- https://github.com/secryst/rababa-models/releases/tag/hebrew.0.1

==== Models

Please download model files:
diacritization_model_arabic.onnx and diacritization_model_hebrew.onnx
 into ../models-data .

==== configs

Download model_arabic.yml and model_hebrew.yml into ../config .

=== Running examples for Arabic

One can diacritize either single strings:

[source,sh]
----
rababa -larabic -t 'قطر'
# or when inside the gem directory during development
bin/rababa -larabic -t 'قطر'
----

Or files as `data/examples.txt` or your own Arabic file (the max string length
is specified in the model and has to match the `max_len` parameter in
`config/models.yaml`):

[source,sh]
----
rababa -f data/example.txt
# or when inside the gem directory during development
bin/rababa -f data/example.txt
----

=== Running examples for Hebrew

[source,sh]
----
rababa -lhebrew --t 'מה שלומך'
rababa -lhebrew --f '../python/data/test/test.txt'
# Substitute rababa with bin/rababa during development
----

One would have to preprocess generic hebraic texts for running Rababa in general.
The code output warning when text is cut off.

=== Additional Parameters
* --config/-c allows for explicit configuration path
* --model_path/-m allows for an explicit path to onnx model


== Training

=== ONNX Models

They can either be built in the `/python` repository or downloaded from the
https://github.com/secryst/rababa-models[releases].

For Hebrew: https://github.com/secryst/rababa-models/releases/tag/hebrew.0.1[release]

Or ONNX model can be generated running the Python
https://github.com/interscript/rababa/blob/main/python/diacritization_model_to_onnx.py[code]
in this library.

It requires to go through some of the steps described in the link above.

=== Parameters

* text to diacritize: "**-t**TEXT", "--text=TEXT",
* path to file to diacritize: "**-f**FILE", "--text_filename=FILE",
* path to ONNX model **Mandatory**: "-mMODEL", "--model_file=MODEL",
* path to config file **Default:config/model.yml**: "-cCONFIG", "--config=CONFIG"

=== Config

==== Players

* `max_len`: `200` -- `600`

** Parameter that has to match the ONNX model built using the
  https://github.com/interscript/rababa/blob/main/python/diacritization_model_to_onnx.py[code]
  and following the `python/README.adoc`.

** Longer sentences will need to be preprocessed, which can be done for
  instance using https://github.com/Hamza5[Hamza5]
  https://github.com/Hamza5/Pipeline-diacritizer/blob/master/pipeline_diacritizer/pipeline_diacritizer.py[code].

** the smaller the faster, the slimmer the NNets code.

Text encoders are only for Arabic:

* text_encoder corresponding to the https://github.com/interscript/rababa/blob/main/python/util/text_encoders.py[rules]:
** `BasicArabicEncoder`
** `ArabicEncoderWithStartSymbol`

* text_cleaner corresponding to https://github.com/interscript/rababa/blob/main/python/util/text_cleaners.py[logics]:
** `basic_cleaners`: remove redundancy in whitespaces and strip string
** `valid_arabic_cleaners`: basic+filter of only Arabic words
