session_name: base

data_directory: "data"
#data_type: "CA_MSA"
log_directory: "log_dir"
load_training_data: true
load_test_data: false
load_validation_data: true
n_training_examples: null # null load all training examples, good for fast loading
n_test_examples: null  # null load all test examples
n_validation_examples: null # null load all validation examples
train_file_name: "clean_data_modern.txt"
test_file_name: "test.txt"
is_data_preprocessed: false # The data file is organized as (original text | text | diacritics)
data_separator: '|' # Required if the data already processed
diacritics_separator: '*'  # Required if the data already processed
#text_encoder: ArabicEncoderWithStartSymbol
#text_cleaner: valid_arabic_cleaners # a white list that uses only Arabic letters, punctuations, and a space
max_len: 600 # sentences larger than this size will not be used
reconcile: true

max_steps: 2_000_000
learning_rate: 0.001
batch_size: 32
adam_beta1: 0.9
adam_beta2: 0.999
use_decay: true
weight_decay: 0.0
embedding_dim: 256
use_prenet: false
prenet_sizes: [512, 256]
cbhg_projections: [128, 256]
cbhg_filters: 16
cbhg_gru_units: 256
post_cbhg_layers_units: [256, 256]
post_cbhg_use_batch_norm: true

use_mixed_precision: false
optimizer_type: Adam
device: cpu

# GEOMETRY
len_input_symbols: 90
len_niqqud_symbols: 16
len_dagesh_symbols: 3
len_sin_symbols: 4

# LOGGING
evaluate_frequency: 5000
evaluate_with_error_rates_frequency: 5000
n_predicted_text_tensorboard: 10 # To be written to the tensorboard
model_save_frequency: 5000
train_plotting_frequency: 50000000 # No plotting for this model
n_steps_avg_losses: [100, 500, 1_000, 5_000] # command line display of average loss values for the last n steps
error_rates_n_batches: 10000 # if calculating error rate is slow, then you can specify the number of batches to be calculated

test_model_path: null # load the last saved model

# Path to model weights file (pytorch model)
# This line is added to support testing without an existing model
model_path: null
train_resume_model_path: null # load last saved model
