session_name: base

data_directory: "data"
data_type: "test"
log_directory: "log_dir"
load_training_data: true
load_test_data: false
load_validation_data: true
n_training_examples: 5 # Using a small number for testing
n_test_examples: null  # null load all test examples
n_validation_examples: null # null load all validation examples
train_file_name: "test.txt"
test_file_name: "test.txt"
is_data_preprocessed: false
data_separator: '|'
diacritics_separator: '*'
text_encoder: HebrewEncoder # Use Hebrew encoder
text_cleaner: basic_cleaners # Adjusted for Hebrew
max_len: 600 # sentences larger than this size will not be used
reconcile: true

max_steps: 50
learning_rate: 0.001
batch_size: 32
adam_beta1: 0.9
adam_beta2: 0.999
use_decay: true
weight_decay: 0.0
embedding_dim: 256
use_prenet: false
prenet_sizes: [512, 256]
cbhg_projections: [128, 256]
cbhg_filters: 16
cbhg_gru_units: 256
post_cbhg_layers_units: [256, 256]
post_cbhg_use_batch_norm: true

use_mixed_precision: false
optimizer_type: Adam
device: cpu  # Using CPU for testing

# GEOMETRY
len_input_symbols: 90
len_niqqud_symbols: 16
len_dagesh_symbols: 3
len_sin_symbols: 4

# LOGGING
evaluate_frequency: 10
evaluate_with_error_rates_frequency: 10
n_predicted_text_tensorboard: 5 # To be written to the tensorboard
model_save_frequency: 10
train_plotting_frequency: 50000000 # No plotting for this model
n_steps_avg_losses: [10, 20, 30, 40] # Reduced for testing
error_rates_n_batches: 5 # Reduced for testing

test_model_path: null # load the last saved model
train_resume_model_path: null # load last saved model
model_path: null
