#!/usr/bin/env ruby

# run text of file diacritization:
#  rababa -t 'قطر' -m '../models-data/diacritization_model.onnx'
#  rababa -f example.csv -m '../models-data/diacritization_model.onnx'

require "rababa/cli"

Rababa::CLI.call
